// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwwxKxIQt-bITQKWN1sXxs5Pc3A3EMuTc',
    appId: '1:515447922918:web:82d98d5a7670316931db27',
    messagingSenderId: '515447922918',
    projectId: 'team-sketch-omma',
    authDomain: 'team-sketch-omma.firebaseapp.com',
    storageBucket: 'team-sketch-omma.firebasestorage.app',
    measurementId: 'G-FK02JTQET8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALx85H--jsrSwAC7NpW5wMjYlhMro5O_0',
    appId: '1:515447922918:android:d4bbc7c9b328579131db27',
    messagingSenderId: '515447922918',
    projectId: 'team-sketch-omma',
    storageBucket: 'team-sketch-omma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ytGIyig1Wib6RepaCGAGso0UCu_FDJA',
    appId: '1:515447922918:ios:6075d897159922a131db27',
    messagingSenderId: '515447922918',
    projectId: 'team-sketch-omma',
    storageBucket: 'team-sketch-omma.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4ytGIyig1Wib6RepaCGAGso0UCu_FDJA',
    appId: '1:515447922918:ios:6075d897159922a131db27',
    messagingSenderId: '515447922918',
    projectId: 'team-sketch-omma',
    storageBucket: 'team-sketch-omma.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwwxKxIQt-bITQKWN1sXxs5Pc3A3EMuTc',
    appId: '1:515447922918:web:87248dabc994ea2b31db27',
    messagingSenderId: '515447922918',
    projectId: 'team-sketch-omma',
    authDomain: 'team-sketch-omma.firebaseapp.com',
    storageBucket: 'team-sketch-omma.firebasestorage.app',
    measurementId: 'G-333VM50W78',
  );
}
